POSVITWeb/Controllers/TransferController.cs
using Newtonsoft.Json;
using POSVITWeb.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace POSVITWeb.Controllers
{
    public class TransferController : Controller
    {
        POSVIT_JTEntities db = new POSVIT_JTEntities();

        public ActionResult AddTransferOut()
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            TransferOutDetailClass transferOutDetail = new TransferOutDetailClass();
            string kodelokasi = Session["kode_lokasi"].ToString();
            var checkfrom = db.tblLokasis.Where(p => p.kodelokasi.Equals(kodelokasi)).FirstOrDefault();
            transferOutDetail.fromstore = checkfrom.nama;
            transferOutDetail.kodefrom = kodelokasi;
            transferOutDetail.tostore = db.tblLokasis
                .Where(p => (!p.kodelokasi.Contains("000") && p.kodelokasi != "PUSAT") && p.initial != "" && 
                !p.kodelokasi.Equals(kodelokasi) && p.aktif == true).ToList();
            transferOutDetail.type = new List<ChooseTypeClass>();
            var typemutasi = db.tblIntegrasiMutasiStoks.ToList();
            for (int i = 0; i < typemutasi.Count; i++)
            {
                ChooseTypeClass chooseType = new ChooseTypeClass();
                chooseType.typename = typemutasi[i].kode;
                transferOutDetail.type.Add(chooseType);
            }
            transferOutDetail.items = getItemFromStore();
            transferOutDetail.trlist = new List<ChooseTransferRequestClass>();
            //var checklokasi = db.tblLokasis.Where(p => p.kodelokasi == kodelokasi).FirstOrDefault();
            //if (checklokasi != null)
            //{
            //    kodelokasi = checklokasi.InTransit;
            //}
            var transferreqlist = (from m in db.tblthMutasiStokTRs.Where(p => p.kodelokasi == kodelokasi)
                                   from fs in db.tblLokasis.Where(p => p.InTransit == m.tujuan)
                                   group new { m } by new
                                   {
                                       m.NoFaktur,
                                       m.nourut,
                                       fs.nama,
                                       m.tgl,
                                       m.keterangan
                                   }
                                   into g
                                   select new
                                   {
                                       g.Key.NoFaktur,
                                       g.Key.nourut,
                                       g.Key.nama,
                                       g.Key.tgl,
                                       g.Key.keterangan,
                                       checktbltdmutasistoktrclose = db.tbltdMutasiStokTRs.Where(p => p.NoFaktur == g.Key.NoFaktur && p.closed == true).ToList().Count,
                                       checktbltdmutasistoktrall = db.tbltdMutasiStokTRs.Where(p => p.NoFaktur == g.Key.NoFaktur).ToList()
                                   }).OrderByDescending(p => p.nourut).ToList();
            //var transferreqlist = db.tblthMutasiStokTRs.Where(p => p.kodelokasi == kodelokasi).OrderByDescending(p => p.nourut).ToList();
            for (int i = 0; i < transferreqlist.Count; i++)
            {
                //string nofakturtr = transferreqlist[i].NoFaktur;
                //var checktbltdmutasistoktrclose = db.tbltdMutasiStokTRs.Where(p => p.NoFaktur == nofakturtr && p.closed == true).ToList().Count;
                //var checktbltdmutasistoktrall = db.tbltdMutasiStokTRs.Where(p => p.NoFaktur == nofakturtr).ToList().Count;
                if (transferreqlist[i].checktbltdmutasistoktrclose != transferreqlist[i].checktbltdmutasistoktrall.Count)
                {
                    ChooseTransferRequestClass transferRequestClass = new ChooseTransferRequestClass();
                    transferRequestClass.nofaktur = transferreqlist[i].NoFaktur;
                    transferRequestClass.fromstore = transferreqlist[i].nama;
                    transferRequestClass.qty = (float)transferreqlist[i].checktbltdmutasistoktrall.Sum(p => p.qty) - (float)transferreqlist[i].checktbltdmutasistoktrall.Sum(p => p.kirim);
                    transferRequestClass.tgl = transferreqlist[i].tgl.ToString("dd-MMM-yyyy HH:mm");
                    transferRequestClass.notes = transferreqlist[i].keterangan;
                    transferOutDetail.trlist.Add(transferRequestClass);
                }
            }
            transferOutDetail.tsomorethantr = Session["tso_eq_tr"].ToString() == "True" ? "t" : "f";
            transferOutDetail.tsogreaterthantr = Session["tso_gt_tr"].ToString() == "True" ? "t" : "f";
            transferOutDetail.tsocopytr = Session["tso_copy_tr"].ToString() == "True" ? "t" : "f";
            transferOutDetail.lockdate = Session["lock_date"].ToString() == "True" ? "t" : "f";
            return View(transferOutDetail);
        }

        //[HttpPost]
        //public ActionResult AddTransferOut(TransferOutDetailClass param)
        //{
        //    if (Session["role_id"] == null)
        //    {
        //        return RedirectToAction("Login");
        //    }
        //    try
        //    {
        //        var dt = DateTime.ParseExact(param.tanggal, "dd/MM/yyyy", CultureInfo.InvariantCulture);
        //        string nofaktur = "TSO/" + param.kodefrom + "/";
        //        var checkpenjualan = db.tblthMutasiStoks
        //            .Where(p => p.kodelokasi == param.kodefrom).ToList().OrderByDescending(p => p.NoFaktur);
        //        if (checkpenjualan.Count() != 0)
        //        {
        //            if (checkpenjualan.First().NoFaktur.StartsWith(nofaktur + dt.ToString("yy") + dt.ToString("MM")))
        //            {
        //                string[] splitfaktur = checkpenjualan.First().NoFaktur.Split('/');
        //                nofaktur = nofaktur + (Int32.Parse(splitfaktur[2]) + 1);
        //            }
        //            else
        //            {
        //                nofaktur = nofaktur + dt.ToString("yy") + dt.ToString("MM") + "00001";
        //            }
        //        }
        //        db.sp_SimpanHeaderMutasiStok(nofaktur, dt, param.comment, Session["user_id"].ToString(), "1",
        //            param.kodefrom, param.kodeto, "", param.tipe);
        //        List<ViewCartClass> PSJD = JsonConvert.DeserializeObject<List<ViewCartClass>>(param.cartstring);
        //        foreach (var dataset in PSJD)
        //        {
        //            db.sp_SimpanDetailMutasiStok(nofaktur, dataset.itemcode, (decimal)dataset.itemqty, "",
        //                dt, Session["kode_lokasi"].ToString(), "");
        //        }
        //        //var userdb = db.musers.Where(p => p.kodelokasi == param.kodelokasi && p.tokenFB != null).ToList();
        //        //for (int i = 0; i < userdb.Count; i++)
        //        //{
        //        //    SendNotifOutput notifresult = sendNotif("Inventory", "Transfer Out Had Succeed", userdb[i].tokenFB, param.transferoutdetail, param.mode);
        //        //}
        //    }
        //    catch (Exception ex)
        //    {

        //    }
        //    return RedirectToAction("TransferOut");
        //}

        public ActionResult SubmitTransferOut(string tanggal, string keterangan, string noreference, string tostore, string type,
            string cart, string mode)
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login");
            }
            bool isValid = true;
            string nofaktur = "";
            string messages = "";
            var dt = DateTime.ParseExact(tanggal, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            dt = DateTime.Now;
            string kodefrom = Session["kode_lokasi"].ToString();
            string initialfrom = Session["initial_lokasi"].ToString();
            nofaktur = "TSO/" + initialfrom + "/";
            var checkpenjualan = db.tblthMutasiStoks
                .Where(p => p.kodelokasi == kodefrom && p.NoFaktur.Contains("TSO")).OrderByDescending(p => p.nourut).ToList();
            if (checkpenjualan.Count() != 0)
            {
                if (checkpenjualan.First().NoFaktur.StartsWith(nofaktur + dt.ToString("yy") + dt.ToString("MM") + dt.ToString("dd")))
                {
                    string[] splitfaktur = checkpenjualan.First().NoFaktur.Split('/');
                    nofaktur = nofaktur + (Int64.Parse(splitfaktur[2]) + 1);
                }
                else
                {
                    nofaktur = nofaktur + dt.ToString("yy") + dt.ToString("MM") + dt.ToString("dd") + "0001";
                }
            }
            else
            {
                nofaktur = nofaktur + dt.ToString("yy") + dt.ToString("MM") + dt.ToString("dd") + "0001";
            }
            var checklokasi = db.tblLokasis.Where(p => p.kodelokasi == tostore).FirstOrDefault();
            string transittostore = tostore;
            if (checklokasi != null)
            {
                transittostore = checklokasi.InTransit;
            }
            var txOptions = new System.Transactions.TransactionOptions();
            txOptions.IsolationLevel = System.Transactions.IsolationLevel.ReadCommitted;
            using (var transaction = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions()
            {
                IsolationLevel = System.Transactions.IsolationLevel.ReadCommitted,
                Timeout = TimeSpan.FromSeconds(30)
            }))
            {
                try
                {

POSVITWeb/Views/Transfer/ChooseItem.cshtml
@model IEnumerable<POSVITWeb.Models.ChooseItemClass>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Asset/js/jquery.min.js"></script>
<script src="~/Asset/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script>
    $(document).ready(function () {
        var rowSelection = $('#dttest').DataTable({
            "responsive": true,
            "language": {
                "paginate": {
                    "previous": '<i class="demo-psi-arrow-left"></i>',
                    "next": '<i class="demo-psi-arrow-right"></i>'
                }
            }
        });
        $('#dttest').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                rowSelection.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');

            }
        });
        $('#demo-dt-delete-btn').appendTo($("div.toolbar"));
        $('#dt-add-btn').appendTo($("div.toolbar"));
        $('#demo-dt-delete-btn').click(function () {
            var data = rowSelection.rows('.selected').data();
            var skuid = data[0][0];
            window.location.href = "@Url.Action("DeleteSite","Home")?siteid=" + skuid;
        });
    })
    function popupshowup(eventid)
    {
        var cek = confirm("Delete This Event?");
        if (cek == true) {
            window.location.href = "@Url.Action("DeleteEvent","Home")?eventid=" + eventid;
        }
        else {

        }
    }
</script>
<div>
    <div>
        <div id="page-content" style="font-size:14px">
            <div class="col-sm-12">
                <div class="panel panel-bordered panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Item List</h3>
                    </div>
                    <div class="panel-body">
                        <a href="@Url.Action("AddEvent", "Home")" class="btn btn-primary fileinput-button dz-clickable" id="dt-add-btn">
                            <i class="fa fa-plus"></i>
                            <span> Add Event</span>
                        </a>
                        <div class="form-group"></div>
                        <table id="dttest" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th width="10px" style="text-align:center">Code</th>
                                    <th width="10px" style="text-align:center">Name</th>
                                    <th width="10px" style="text-align:center">Category</th>
                                    <th width="10px" style="text-align:center">Produsen</th>
                                    <th width="10px" style="text-align:center">Stock</th>
                                    <th width="10px" style="text-align:center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td style="text-align:center">@item.kodebarang</td>
                                    <td>@item.namabarang</td>
                                    <td>@item.namakategori</td>
                                    <td style="text-align:center">@item.namaprodusen</td>
                                    <td style="text-align:center">@item.stock</td>
                                    <td style="text-align:center">
                                        <a class="btn btn-xs btn-primary add-tooltip" data-toggle="tooltip" href="~/Home/DetailsEvent?eventid=@item.kodebarang" data-original-title="Details" data-container="body"><i class="fa fa-edit"></i></a>&nbsp;&nbsp;&nbsp;<a class="btn btn-xs btn-danger add-tooltip" data-toggle="tooltip" onclick="popupshowup(@item.kodebarang)" data-original-title="Deactivate" data-container="body"><i class="fa fa-warning"></i></a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

POSVITWeb/Views/Transfer/TransferIn.cshtml
@model IEnumerable<POSVITWeb.Models.TransferOutClass>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Asset/js/jquery.min.js"></script>
<script src="~/Asset/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script>
    $(document).ready(function () {
        var rowSelection = $('#dttest').DataTable({
            "responsive": true,
            "language": {
                "paginate": {
                    "previous": '<i class="demo-psi-arrow-left"></i>',
                    "next": '<i class="demo-psi-arrow-right"></i>'
                }
            },
            "order": [[1, "desc"]]
        });
        $('#dttest').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                rowSelection.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');

            }
        });
        $('#demo-dt-delete-btn').appendTo($("div.toolbar"));
        $('#dt-add-btn').appendTo($("div.toolbar"));
        $('#demo-dt-delete-btn').click(function () {
            var data = rowSelection.rows('.selected').data();
            var skuid = data[0][0];
            window.location.href = "@Url.Action("DeleteSite","Home")?siteid=" + skuid;
        });
    })
    function popupshowup(eventid)
    {
        var cek = confirm("Delete This Event?");
        if (cek == true) {
            window.location.href = "@Url.Action("DeleteEvent","Home")?eventid=" + eventid;
        }
        else {

        }
    }
</script>
<div>
    <div>
        <div id="page-content" style="font-size:14px">
            <div class="col-sm-12">
                <div class="panel panel-bordered panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">List of Transfer In</h3>
                    </div>
                    @if (ViewBag.Message != null)
                    {
                        <div class="mar-ver pad-btm">
                            <h3 class="h4 mar-no">@ViewBag.Message</h3>
                        </div>
                    }
                    <div class="panel-body">
                        <a href="@Url.Action("AddTransferIn", "Transfer")" class="btn btn-primary fileinput-button dz-clickable" id="dt-add-btn">
                            <i class="fa fa-plus"></i>
                            <span> Create Transfer In</span>
                        </a>
                        <div class="form-group"></div>
                        <table id="dttest" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th width="10px" style="text-align:center">Doc No.</th>
                                    <th width="10px" style="text-align:center" hidden>No Faktur</th>
                                    <th width="10px" style="text-align:center">Date</th>
                                    <th width="10px" style="text-align:center">Ref. No.</th>
                                    @*<th width="10px" style="text-align:center">Date Ref</th>*@
                                    <th width="10px" style="text-align:center">Notes</th>
                                    @*<th width="10px" style="text-align:center">From Store</th>*@
                                    <th width="10px" style="text-align:center">From</th>
                                    <th width="10px" style="text-align:center">Total Qty</th>
                                    <th width="10px" style="text-align:center">Created By</th>
                                    <th width="10px" style="text-align:center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td style="text-align:center">@item.nofaktur</td>
                                    <td style="text-align:center" hidden>@item.nourut</td>
                                    <td style="text-align:center">@item.modidate</td>
                                    <td style="text-align:center">@item.nofakturtr</td>
                                    @*<td style="text-align:center">@item.tanggaltr</td>*@
                                    <td>@item.keterangan</td>
                                    <td style="text-align:center">@item.namaawal</td>
                                    <td style="text-align:center">@item.totalitemdetail</td>
                                    <td style="text-align:center">@item.usernama</td>
                                    <td style="text-align:center">
                                        <a class="btn btn-xs btn-primary add-tooltip" data-toggle="tooltip" href="~/Transfer/DetailsTransferIn?nofaktur=@item.nofaktur" data-original-title="Transfer In" data-container="body"><i class="fa fa-edit"></i></a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

POSVITWeb/Views/Transfer/TransferOut.cshtml
@model IEnumerable<POSVITWeb.Models.TransferOutClass>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Asset/js/jquery.min.js"></script>
<script src="~/Asset/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script>
    $(document).ready(function () {
        var rowSelection = $('#dttest').DataTable({
            "responsive": true,
            "language": {
                "paginate": {
                    "previous": '<i class="demo-psi-arrow-left"></i>',
                    "next": '<i class="demo-psi-arrow-right"></i>'
                }
            },
            "order": [[1, "desc"]]
        });
        $('#dttest').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                rowSelection.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');

            }
        });
        $('#demo-dt-delete-btn').appendTo($("div.toolbar"));
        $('#dt-add-btn').appendTo($("div.toolbar"));
        $('#demo-dt-delete-btn').click(function () {
            var data = rowSelection.rows('.selected').data();
            var skuid = data[0][0];
            window.location.href = "@Url.Action("DeleteSite","Home")?siteid=" + skuid;
        });
    })
    function popupshowup(eventid)
    {
        var cek = confirm("Delete This Event?");
        if (cek == true) {
            window.location.href = "@Url.Action("DeleteEvent","Home")?eventid=" + eventid;
        }
        else {

        }
    }
</script>
<div>
    <div>
        <div id="page-content" style="font-size:14px">
            <div class="col-sm-12">
                <div class="panel panel-bordered panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">List of Transfer Out</h3>
                    </div>
                    @if (ViewBag.Message != null)
                    {
                        <div class="mar-ver pad-btm">
                            <h3 class="h4 mar-no">@ViewBag.Message</h3>
                        </div>
                    }
                    <div class="panel-body">
                        <a href="@Url.Action("AddTransferOut", "Transfer")" class="btn btn-primary fileinput-button dz-clickable" id="dt-add-btn">
                            <i class="fa fa-plus"></i>
                            <span> Create Transfer Out</span>
                        </a>
                        <div class="form-group"></div>
                        <table id="dttest" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th width="10px" style="text-align:center">Doc No.</th>
                                    <th width="10px" style="text-align:center" hidden>No Faktur</th>
                                    <th width="10px" style="text-align:center">Date</th>
                                    <th width="10px" style="text-align:center">Ref No.</th>
                                    <th width="10px" style="text-align:center">Notes</th>
                                    <th width="10px" style="text-align:center">To Store</th>
                                    <th width="10px" style="text-align:center" hidden>Total Qty</th>
                                    <th width="10px" style="text-align:center">Status</th>
                                    <th width="10px" style="text-align:center">Created By</th>
                                    <th width="10px" style="text-align:center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td style="text-align:center">@item.nofaktur</td>
                                    <td style="text-align:center" hidden>@item.nourut</td>
                                    <td style="text-align:center">@item.modidate</td>
                                    <td style="text-align:center">@item.nofakturtr</td>
                                    @*<td style="text-align:center">@item.tanggaltr</td>*@
                                    <td>@item.keterangan</td>
                                    <td>@item.namaakhir</td>
                                    <td style="text-align:center" hidden>@item.totalitemdetail</td>
                                    <td style="text-align:center">@item.status</td>
                                    <td style="text-align:center">@item.usernama</td>
                                    <td style="text-align:center">
                                        <a class="btn btn-xs btn-primary add-tooltip" data-toggle="tooltip" href="~/Transfer/DetailsTransferOut?nofaktur=@item.nofaktur" data-original-title="Transfer Out" data-container="body"><i class="fa fa-edit"></i></a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

POSVITWeb/Views/Transfer/TransferRequest.cshtml
@model IEnumerable<POSVITWeb.Models.TransferOutClass>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Asset/js/jquery.min.js"></script>
<script src="~/Asset/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script>
    $(document).ready(function () {
        var rowSelection = $('#dttest').DataTable({
            "responsive": true,
            "language": {
                "paginate": {
                    "previous": '<i class="demo-psi-arrow-left"></i>',
                    "next": '<i class="demo-psi-arrow-right"></i>'
                }
            },
            "order": [[1, "desc"]]
        });
        $('#dttest').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                rowSelection.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');

            }
        });
        $('#demo-dt-delete-btn').appendTo($("div.toolbar"));
        $('#dt-add-btn').appendTo($("div.toolbar"));
        $('#demo-dt-delete-btn').click(function () {
            var data = rowSelection.rows('.selected').data();
            var skuid = data[0][0];
            window.location.href = "@Url.Action("DeleteSite","Home")?siteid=" + skuid;
        });
    })
    function popupshowup(nofaktur)
    {
        var cek = confirm("Close This Transfer Request " + nofaktur + "?");
        if (cek == true) {
            window.location.href = "@Url.Action("CloseManualTranferRequest","Transfer")?nofaktur=" + nofaktur;
        }
        else {

        }
    }
</script>
<div>
    <div>
        <div id="page-content" style="font-size:14px">
            <div class="col-sm-12">
                <div class="panel panel-bordered panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">List of Transfer Request</h3>
                    </div>
                    @if (ViewBag.Message != null)
                    {
                        <div class="mar-ver pad-btm">
                            <h3 class="h4 mar-no">@ViewBag.Message</h3>
                        </div>
                    }
                    <div class="panel-body">
                        <a href="@Url.Action("AddTransferRequest", "Transfer")" class="btn btn-primary fileinput-button dz-clickable" id="dt-add-btn">
                            <i class="fa fa-plus"></i>
                            <span> Create Transfer Request</span>
                        </a>
                        <div class="form-group"></div>
                        <table id="dttest" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th width="10px" style="text-align:center">Doc No.</th>
                                    <th width="10px" style="text-align:center" hidden>No Faktur</th>
                                    <th width="10px" style="text-align:center">Date</th>
                                    <th width="10px" style="text-align:center">Notes</th>
                                    <th width="10px" style="text-align:center">For</th>
                                    <th width="10px" style="text-align:center">Total Qty</th>
                                    <th width="10px" style="text-align:center">Status</th>
                                    <th width="10px" style="text-align:center">Created By</th>
                                    <th width="10px" style="text-align:center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td style="text-align:center">@item.nofaktur</td>
                                    <td style="text-align:center" hidden>@item.nourut</td>
                                    <td style="text-align:center">@item.modidate</td>
                                    <td>@item.keterangan</td>
                                    <td>@item.namaawal</td>
                                    <td style="text-align:right">@item.totalitemdetail</td>
                                    <td style="text-align:center">@item.status</td>
                                    <td style="text-align:center">@item.usernama</td>
                                    <td style="text-align:center">
                                        <a class="btn btn-xs btn-primary add-tooltip" data-toggle="tooltip" href="~/Transfer/DetailsTransferRequest?nofaktur=@item.nofaktur" data-original-title="Transfer Request" data-container="body"><i class="fa fa-edit"></i></a>
                                        @*&nbsp;&nbsp;&nbsp;
                                        @if (item.status == "Open")
                                        {
                                            <a class="btn btn-xs btn-danger add-tooltip" data-toggle="tooltip" onclick="popupshowup('@item.nofaktur')" data-original-title="Close" data-container="body"><i class="fa fa-warning"></i></a>
                                        }*@
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>