POSVITWeb/Controllers/StokController.cs
using Microsoft.Ajax.Utilities;
using POSVITWeb.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace POSVITWeb.Controllers
{
    public class StokController : Controller
    {
        POSVIT_JTEntities db = new POSVIT_JTEntities();

        public ActionResult AddStokOpname()
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            TransferOutDetailClass transferOutDetail = new TransferOutDetailClass();
            string kodelokasi = Session["kode_lokasi"].ToString();
            var checkfrom = db.tblLokasis.Where(p => p.kodelokasi.Equals(kodelokasi)).FirstOrDefault();
            transferOutDetail.fromstore = checkfrom.nama;
            transferOutDetail.kodefrom = kodelokasi;
            transferOutDetail.tostore = db.tblLokasis
                .Where(p => !p.kodelokasi.Contains("000") && !p.kodelokasi.Contains("T")).ToList();
            transferOutDetail.type = new List<ChooseTypeClass>();
            var typeopname = db.tblIntegrasiOpnames.ToList();
            for (int i = 0; i < typeopname.Count; i++)
            {
                ChooseTypeClass chooseType = new ChooseTypeClass();
                chooseType.typename = typeopname[i].kode;
                transferOutDetail.type.Add(chooseType);
            }
            return View(transferOutDetail);
        }

        public ActionResult AddGoodsReturn()
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            AddGoodsReturnClass transferOutDetail = new AddGoodsReturnClass();
            string kodelokasi = Session["kode_lokasi"].ToString();
            var checklokasi = db.tblLokasis.Where(p => p.kodelokasi == kodelokasi).FirstOrDefault();
            if (checklokasi != null)
            {
                transferOutDetail.kodelokasi = checklokasi.kodelokasi;
                transferOutDetail.namalokasi = checklokasi.nama;
            }
            var checksupplier = db.tblSuppliers.Where(p => p.aktif == true).OrderBy(p => p.nama).ToList();
            transferOutDetail.suppliers = new List<GetSupplierClass>();
            for (int i = 0; i < checksupplier.Count; i++)
            {
                GetSupplierClass chooseType = new GetSupplierClass();
                chooseType.suppliercode = checksupplier[i].kodesupplier;
                chooseType.suppliername = checksupplier[i].nama;
                chooseType.supplierPIC = checksupplier[i].namacontact1;
                transferOutDetail.suppliers.Add(chooseType);
            }
            transferOutDetail.lockdate = Session["lock_date"].ToString() == "True" ? "t" : "f";
            return View(transferOutDetail);
        }

        public ActionResult AddStokOpnameTemporary()
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            TransferOutDetailClass transferOutDetail = new TransferOutDetailClass();
            string kodelokasi = Session["kode_lokasi"].ToString();
            var checkfrom = db.tblLokasis.Where(p => p.kodelokasi.Equals(kodelokasi)).FirstOrDefault();
            transferOutDetail.fromstore = checkfrom.nama;
            transferOutDetail.kodefrom = kodelokasi;
            transferOutDetail.tostore = db.tblLokasis
                .Where(p => !p.kodelokasi.Contains("000") && !p.kodelokasi.Contains("T")).ToList();
            return View(transferOutDetail);
        }

        public ActionResult AddStokMasuk()
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            TransferOutDetailClass transferOutDetail = new TransferOutDetailClass();
            string kodelokasi = Session["kode_lokasi"].ToString();
            var checkfrom = db.tblLokasis.Where(p => p.kodelokasi.Equals(kodelokasi)).FirstOrDefault();
            transferOutDetail.fromstore = checkfrom.nama;
            transferOutDetail.kodefrom = kodelokasi;
            transferOutDetail.tostore = db.tblLokasis
                .Where(p => !p.kodelokasi.Contains("000") && !p.kodelokasi.Contains("T")).ToList();
            transferOutDetail.type = new List<ChooseTypeClass>();
            var typeopname = db.tblIntegrasiOpnames.ToList();
            for (int i = 0; i < typeopname.Count; i++)
            {
                ChooseTypeClass chooseType = new ChooseTypeClass();
                chooseType.typename = typeopname[i].kode;
                transferOutDetail.type.Add(chooseType);
            }
            return View(transferOutDetail);
        }

        public ActionResult DetailsStokOpname(string nofaktur)
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            TransferOutDetailClass transferOutDetail = new TransferOutDetailClass();
            var solotr = (from m in db.tblthOpnames.Where(p => p.NoFaktur == nofaktur)
                          from l1 in db.tblLokasis.Where(p => p.kodelokasi == m.kodelokasi)
                          group new { m, l1 } by new
                          {
                              m.NoFaktur,
                              m.tgl,
                              m.keterangan,
                              kodefrom = l1.kodelokasi,
                              namafrom = l1.nama,
                              m.tipeopname,
                              m.userid,
                              m.modidate,
                              m.total
                          }
                           into g
                          select new
                          {
                              g.Key.NoFaktur,
                              g.Key.tgl,
                              g.Key.keterangan,
                              g.Key.kodefrom,
                              g.Key.namafrom,
                              g.Key.tipeopname,
                              g.Key.modidate,
                              g.Key.userid,
                              g.Key.total
                          }).FirstOrDefault();
            if (solotr != null)
            {
                transferOutDetail.fromstore = solotr.namafrom;
                transferOutDetail.tipe = solotr.tipeopname;
                transferOutDetail.comment = solotr.keterangan;
                transferOutDetail.nofaktur = solotr.NoFaktur;
                transferOutDetail.tanggal = solotr.tgl.ToString("dd-MMM-yyyy");
                transferOutDetail.userid = solotr.userid;
                transferOutDetail.total = solotr.total;
                transferOutDetail.createtime = solotr.modidate.ToString("dd-MMM-yyyy");
                transferOutDetail.carts = new List<ViewCartClass>();
                var detailstr = (from k in db.tbltdOpnames.Where(p => p.NoFaktur == nofaktur)
                                 from e in db.tblHBarangs.Where(p => p.kodebarang == k.kodebarang)
                                 group new { e, k } by new
                                 {
                                     e.kodebarang,
                                     e.nama,
                                     k.harga,
                                     k.stok,
                                     k.qty
                                 }
                                 into g
                                 select new
                                 {
                                     g.Key.kodebarang,
                                     g.Key.nama,
                                     g.Key.harga,
                                     g.Key.stok,
                                     g.Key.qty,
                                     totalharga = g.Key.qty * g.Key.harga
                                 }).ToList();
                int totalstok = 0;
                int totalqty = 0;
                for (int i = 0; i < detailstr.Count; i++)
                {
                    ViewCartClass viewCartClass = new ViewCartClass();
                    viewCartClass.itemcode = detailstr[i].kodebarang;
                    viewCartClass.itemname = detailstr[i].nama;
                    viewCartClass.itemprice = (double)detailstr[i].harga;
                    viewCartClass.itemstok = (int)detailstr[i].stok;
                    viewCartClass.itemqty = (int)detailstr[i].qty;
                    viewCartClass.itemtotalprice = (int)detailstr[i].totalharga;
                    transferOutDetail.carts.Add(viewCartClass);
                    totalstok = totalstok + (int)detailstr[i].stok;
                    totalqty = totalqty + (int)detailstr[i].qty;
                }
                transferOutDetail.totalqty = totalstok;
                transferOutDetail.totalqtykirim = totalqty;
            }
            return View(transferOutDetail);
        }

        public ActionResult DetailsGoodsReturn(string nofaktur)
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            AddGoodsReturnClass transferOutDetail = new AddGoodsReturnClass();
            var solotr = (from m in db.tblthOpnames.Where(p => p.NoFaktur == nofaktur)
                          from l2 in db.tblSuppliers.Where(p => p.kodesupplier == m.kodesupplier)
                          from l1 in db.tblLokasis.Where(p => p.kodelokasi == m.kodelokasi)
                          from l3 in db.musers.Where(p => p.muserid == m.userid)
                          group new { m, l1 } by new
                          {
                              m.NoFaktur,
                              m.tgl,
                              m.keterangan,

POSVITWeb/Views/Stok/DetailsGRPO.cshtml
@model POSVITWeb.Models.GoodReceiptPODetailClass
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Asset/js/jquery.min.js"></script>
<script src="~/Asset/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="~/Asset/js/jquery-3.1.1.js" type="text/javascript"></script>
<script src="~/Asset/js/jquery-1-8-23-ui.min.js" type="text/javascript"></script>
<script src="~/Asset/js/bootstrap-datepicker.js" type="text/javascript"></script>
<link href="@Url.Content("~/Content/jquery-ui.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/bootstrap-datetimepicker.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Asset/css/jquery.dataTables.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/buttons.datatable.min.css")" rel="stylesheet" type="text/css" />
<script src="~/Asset/js/jquery.datatable.min.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script src="~/Asset/js/datatable.buttons.min.js"></script>
<script src="~/Asset/js/buttons.flash.min.js"></script>
<script src="~/Asset/js/buttons.html5.min.js"></script>
<script src="~/Asset/js/buttons.print.min.js"></script>
<script src="~/Asset/js/jszip.min.js"></script>
<script src="~/Asset/js/pdfmake.min.js"></script>
<script src="~/Asset/js/vfs_font.js"></script>

<script src="~/Asset/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script>
    var rowSelection;
    var rowSelection2;
    var nofaktur = '';
    $(document).ready(function () {
        //var rowSelection = $('#dttest').DataTable({
        //    "ajax": {
        //        "url": "../Transfer/getItemFromStore/",
        //        "dataSrc": ""
        //    },
        //    "columns": [{
        //        "data": "kodebarang"
        //    }, {
        //        "data": "namabarang"
        //    }, {
        //        "data": "namakategori"
        //    }, {
        //        "data": "namaprodusen"
        //    }, {
        //        "data": "stock"
        //    }]
        //});
        nofaktur = document.getElementById("txtnofaktur").value;
        var counter = 1;
        rowSelection = $('#dttest').DataTable();
        rowSelection2 = $('#dttest2').DataTable({
            "responsive": true,
            "language": {
                "paginate": {
                    "previous": '<i class="demo-psi-arrow-left"></i>',
                    "next": '<i class="demo-psi-arrow-right"></i>'
                }
            },
            dom: 'Bfrtip',
            buttons: [
                {
                    extend: 'print',
                    title: 'No Faktur : ' + nofaktur
                }
            ]
        });
        $('#dttest2').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                rowSelection2.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');

            }
        });
        $('#demo-dt-delete-btn').appendTo($("div.toolbar"));
        $('#dt-add-btn').appendTo($("div.toolbar"));
        $('#demo-dt-delete-btn').click(function () {
            var data = rowSelection2.rows('.selected').data();
            var skuid = data[0][0];
            window.location.href = "@Url.Action("DeleteSite","Home")?siteid=" + skuid;
        });
        $('#dttest').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                rowSelection.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });
        $('#btnprint').click(function () {
            var textbox = '<input type="number" class="txtBox" value="1" style="text-align:center">';
            var data = rowSelection.rows('.selected').data();
            var getcart = document.getElementById("cart").value;
            if (getcart.length == 0) {
                $('#cart').val(data[0].kodebarang);
                rowSelection2.row.add([
                    data[0].kodebarang, data[0].namabarang, textbox
                ]).draw(false);
                counter++;
            }
            else {
                if (getcart.indexOf(data[0][0]) == -1) {
                    $('#cart').val(getcart + ";" + data[0].kodebarang);
                    rowSelection2.row.add([
                        data[0].kodebarang, data[0].namabarang, textbox
                    ]).draw(false);
                    counter++;
                }
            }
        });
        $('#btndeletecart').click(function () {
            rowSelection2.row('.selected').remove().draw(false);
        });
        $('#btnSaveItem').click(function () {
            var getdate = document.getElementById("datepicker1").value;
            var getcomment = document.getElementById("txtcomment").value;
            var dropdown = document.getElementById("dropdowntipe8");
            var gettostore = dropdown.options[dropdown.selectedIndex].value;
            var dropdown2 = document.getElementById("dropdowntipe4");
            var gettype = dropdown2.options[dropdown2.selectedIndex].value;
            var data = rowSelection2.rows().data();
            var cart = '';
            for (var i = 0; i < data.length; i++) {
                if (i == 0) {
                    cart = data[i][0] + '$' + rowSelection2.cell(i, 2).nodes().to$().find('input').val();
                }
                else {
                    cart = cart + ';' + data[i][0] + '$' + rowSelection2.cell(i, 2).nodes().to$().find('input').val();
                }
                //alert(rowSelection2.cell(i, 2).nodes().to$().find('input').val());
            }
            window.location.href = "@Url.Action("SubmitTransferRequest","Transfer")?tanggal=" + getdate + "&keterangan=" +
                getcomment + "&tostore=" + gettostore + "&type=" + gettype + "&cart=" + cart;
        });
        $('#btncancel').click(function () {
             window.location.href = "@Url.Action("GRPO", "Stok")";
        });
    })
    $(function () {
        $("#datepicker1").datepicker({
            format: 'dd/mm/yyyy'
        });
    });
    function onchangeevent8()
    {
        rowSelection2.clear().draw();
        var getreference = document.getElementById("dropdowntipe8");
        var getvalue = getreference.options[getreference.selectedIndex].value;
        $.getJSON("@Url.Action("getItemFromStoreTR", "Transfer")?kodelokasi=" + getvalue, function (data) {
            rowSelection.destroy();
            rowSelection = $('#dttest').DataTable({
                data: data,
                columns: [
                    { "data": "kodebarang" },
                    { "data": "namabarang" },
                    { "data": "namakategori" },
                    { "data": "namaprodusen" },
                    { "data": "stock" }
                ]
            });
            //for (var i = 0; i < data.length; i++) {
            //    rowSelection.row.add([
            //        data[i].kodebarang, data[i].namabarang, data[i].namakategori, data[i].namaprodusen, data[i].stock
            //    ]).draw(false);
            //}
        });
    }

    function onclickprint() {
        window.print();
    }
</script>
<div>
    <div>
        <div id="page-content" style="font-size:14px">
            <div class="col-sm-12">
                <div class="panel panel-bordered panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Details GRPO</h3>
                    </div>
                    @using (Html.BeginForm("AddTransferOut", "Transfer", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                    {
                        <div class="panel-body">
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="demo-hor-inputemail">No Faktur</label>
                                <div class="col-sm-7">
                                    @Html.TextBoxFor(model => model.nofaktur, new { @type = "text", @class = "form-control", @id = "txtnofaktur", @onchange = "onchangedatetime1()", @required = "required", @disabled = "true" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="demo-hor-inputemail">Date</label>
                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.tanggal, new { @type = "text", @class = "form-control", @id = "datepicker1", @onchange = "onchangedatetime1()", @required = "required", @disabled = "true" })
                                </div>
                                <label class="col-sm-1 control-label" for="demo-hor-inputemail">Comment</label>
                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.keterangan, new { @type = "text", @class = "form-control", @id = "txtcomment", @required = "required", @maxlength = "50", @disabled = "true" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="demo-hor-inputemail">Vendor</label>
                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.vendorname, new { @type = "text", @class = "form-control", @id = "txttipe", @required = "required", @maxlength = "50", @disabled = "true" })
                                </div>
                                <label class="col-sm-1 control-label" for="demo-hor-inputemail">Total PO</label>
                                <div class="col-sm-3">
                                    @Html.TextBoxFor(model => model.totalpo, new { @type = "text", @class = "form-control", @id = "txttipe", @required = "required", @maxlength = "50", @disabled = "true" })
                                </div>
                            </div>
                            <div class="form-group"></div>
                            <table id="dttest2" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th width="10px" style="text-align:center">Code</th>
                                        <th width="10px" style="text-align:center">Name</th>
                                        <th width="10px" style="text-align:center" hidden>Order</th>
                                        <th width="10px" style="text-align:center">Qty</th>
                                        <th width="10px" style="text-align:center">UoM</th>
                                        <th width="10px" style="text-align:center">Reff</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.items)
                                    {
                                        <tr>
                                            <td style="text-align:center">@item.kodebarang</td>
                                            <td>@item.namabarang</td>
                                            <td style="text-align:center" hidden>@item.order</td>
                                            <td style="text-align:center">@item.qtyterima</td>
                                            <td style="text-align:center">@item.satuan</td>
                                            <td style="text-align:center">@item.poreff</td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th></th>
                                        <th style="text-align:center;">Total</th>
                                        <th hidden></th>
                                        <th style="text-align:center">@Html.ValueFor(model => model.totalqty)</th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <div class="panel-footer text-right">
                            <div class="box-inline">
                                <button type="button" id="btncancel" class="btn btn-danger" onclick="onclickcancel()"> Back</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

    </div>
</div>

POSVITWeb/Views/Stok/GRPO.cshtml
@model IEnumerable<POSVITWeb.Models.GoodReceiptPOClass>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Asset/js/jquery.min.js"></script>
<script src="~/Asset/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script>
    $(document).ready(function () {
        var rowSelection = $('#dttest').DataTable({
            "responsive": true,
            "language": {
                "paginate": {
                    "previous": '<i class="demo-psi-arrow-left"></i>',
                    "next": '<i class="demo-psi-arrow-right"></i>'
                }
            },
            "order": [[7, "desc"]]
        });
        $('#dttest').on('click', 'tr', function () {
            if ($(this).hasClass('selected')) {
                $(this).removeClass('selected');
            }
            else {
                rowSelection.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');

            }
        });
        $('#demo-dt-delete-btn').appendTo($("div.toolbar"));
        $('#dt-add-btn').appendTo($("div.toolbar"));
        $('#demo-dt-delete-btn').click(function () {
            var data = rowSelection.rows('.selected').data();
            var skuid = data[0][0];
            window.location.href = "@Url.Action("DeleteSite","Home")?siteid=" + skuid;
        });
    })
    function popupshowup(eventid)
    {
        var cek = confirm("Delete This Event?");
        if (cek == true) {
            window.location.href = "@Url.Action("DeleteEvent","Home")?eventid=" + eventid;
        }
        else {

        }
    }
</script>
<div>
    <div>
        <div id="page-content" style="font-size:14px">
            <div class="col-sm-12">
                <div class="panel panel-bordered panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Goods Receipt PO</h3>
                    </div>
                    @if (ViewBag.Message != null)
                    {
                        <div class="mar-ver pad-btm">
                            <h3 class="h4 mar-no">@ViewBag.Message</h3>
                        </div>
                    }
                    <div class="panel-body">
                        <a href="@Url.Action("AddGRPO", "Stok")" class="btn btn-primary fileinput-button dz-clickable" id="dt-add-btn">
                            <i class="fa fa-plus"></i>
                            <span> Create GRPO</span>
                        </a>
                        <div class="form-group"></div>
                        <table id="dttest" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th width="10px" style="text-align:center">Doc No.</th>
                                    <th width="10px" style="text-align:center">Date</th>
                                    <th width="10px" style="text-align:center">Notes</th>
                                    <th width="10px" style="text-align:center">Vendor</th>
                                    <th width="10px" style="text-align:center">Total Qty</th>
                                    <th width="10px" style="text-align:center">Created By</th>
                                    <th width="10px" style="text-align:center">Action</th>
                                    <th width="10px" style="text-align:center" hidden>Doc No.</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td style="text-align:center">@item.nofaktur</td>
                                    <td style="text-align:center">@item.tanggal</td>
                                    <td>@item.keterangan</td>
                                    <td>@item.vendor</td>
                                    <td style="text-align:right">@item.totalitem</td>
                                    <td style="text-align:center">@item.usernama</td>
                                    <td style="text-align:center">
                                        <a class="btn btn-xs btn-primary add-tooltip" data-toggle="tooltip" href="~/Stok/DetailsGRPO?nofaktur=@item.nofaktur" data-original-title="GRPO" data-container="body"><i class="fa fa-edit"></i></a>
                                    </td>
                                    <td hidden>@item.nourut</td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>