POSVITWeb/Controllers/MasterDataController.cs
using ImageResizer;
using POSVITWeb.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POSVITWeb.Controllers
{
    public class MasterDataController : Controller
    {
        POSVIT_JTEntities db = new POSVIT_JTEntities();

        public ActionResult ItemMaster()
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            List<ItemMasterClass> chooseitems = new List<ItemMasterClass>();
            string kodefrom = Session["kode_lokasi"].ToString();
            var itemdb = (from m in db.tblHBarangs.Where(p => p.aktif == true && p.FirmCode != -1)
                          from l1 in db.tblKategoris.Where(p => p.kodekategori == m.kodekategori)
                          from s in db.tblSuppliers.Where(p => p.kodesupplier == m.kodesupplier).DefaultIfEmpty()
                          from ls in db.tblLokasiKategoris.Where(p => p.kodelokasi == kodefrom && p.kodekategori == m.kodekategori)
                          from lp in db.tblLokasiProdusens.Where(p => p.kodelokasi == kodefrom && p.kodeprodusen == m.kodeprodusen)
                          from st in db.tblStoks.Where(p => p.kodelokasi == kodefrom && p.kodebarang == m.kodebarang)
                          group new { m, l1 } by new
                          {
                              m.kodebarang,
                              m.nama,
                              kodekategori = l1.kodekategori,
                              namaketegori = l1.nama,
                              m.satuan,
                              m.hargajual,
                              stok = (int)st.stokmasuk - (int)st.stokkeluar
                          }
                          into g
                          select new
                          {
                              g.Key.kodebarang,
                              g.Key.nama,
                              g.Key.kodekategori,
                              g.Key.namaketegori,
                              g.Key.satuan,
                              g.Key.hargajual,
                              g.Key.stok
                          }).OrderBy(p => p.kodebarang).ToList();
            foreach (var itemdbs in itemdb)
            {
                var soloitem = new ItemMasterClass
                {
                    kodebarang = itemdbs.kodebarang,
                    nama = itemdbs.nama,
                    kodekategori = itemdbs.kodekategori,
                    namakategori = itemdbs.namaketegori,
                    satuan = itemdbs.satuan,
                    strharga = Convert.ToDecimal((double)itemdbs.hargajual).ToString("#,###"),
                    stok = itemdbs.stok
                };
                chooseitems.Add(soloitem);
            }
            return View(chooseitems);
        }

        public ActionResult DetailsItemMaster(string kodebarang)
        {
            if (Session["role_id"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ItemMasterDetailsClass chooseitems = new ItemMasterDetailsClass();
            string kodefrom = Session["kode_lokasi"].ToString();
            var itemdb = (from m in db.tblHBarangs.Where(p => p.kodebarang == kodebarang)
                          from l1 in db.tblKategoris.Where(p => p.kodekategori == m.kodekategori)
                          group new { m, l1 } by new
                          {
                              m.kodebarang,
                              m.nama,
                              kodekategori = l1.kodekategori,
                              namaketegori = l1.nama,
                              m.satuan,
                              m.hargajual,
                              kodevendor = m.kodesupplier,
                              m.itemcode
                          }
                          into g
                          select new
                          {
                              g.Key.kodebarang,
                              g.Key.nama,
                              g.Key.kodekategori,
                              g.Key.namaketegori,
                              g.Key.satuan,
                              g.Key.hargajual,
                              g.Key.kodevendor,
                              g.Key.itemcode,
                              supplier = db.tblSuppliers.Where(p => p.kodesupplier == g.Key.kodevendor).FirstOrDefault()
                          }).FirstOrDefault();
            if (itemdb != null)
            {
                chooseitems.kodebarang = itemdb.kodebarang;
                chooseitems.realkodebarang = itemdb.kodebarang;
                chooseitems.nama = itemdb.nama;
                chooseitems.realnama = itemdb.nama;
                chooseitems.kodekategori = itemdb.kodekategori;
                chooseitems.namakategori = itemdb.namaketegori;
                chooseitems.satuan = itemdb.satuan;
                chooseitems.strharga = Convert.ToDecimal((double)itemdb.hargajual).ToString("#,###");
                chooseitems.harga = (double)itemdb.hargajual;
                chooseitems.stok = 0;
                if (itemdb.supplier != null)
                {
                    chooseitems.kodevendor = itemdb.supplier.kodesupplier;
                    chooseitems.namavendor = itemdb.supplier.nama;
                }
                else
                {
                    chooseitems.kodevendor = "";
                    chooseitems.namavendor = "-";
                }
                chooseitems.itemcode = itemdb.itemcode;
                chooseitems.stocks = new List<ItemMasterStockDetailsClass>();
                var checkstokloc = (from m in db.tblStoks.Where(p => p.kodebarang == itemdb.kodebarang)
                                    from l1 in db.tblLokasis.Where(p => p.kodelokasi == m.kodelokasi)
                                    group new { m, l1 } by new
                                    {
                                        l1.kodelokasi,
                                        l1.nama,
                                        stok = m.stokmasuk - m.stokkeluar
                                    }
                                    into g
                                    select new
                                    {
                                        g.Key.kodelokasi,
                                        g.Key.nama,
                                        g.Key.stok
                                    }).OrderByDescending(p => p.nama).ToList();
                for (int i = 0; i < checkstokloc.Count; i++)
                {
                    if ((int)checkstokloc[i].stok > 0)
                    {
                        ItemMasterStockDetailsClass itemMasterStock = new ItemMasterStockDetailsClass();
                        itemMasterStock.kodelokasi = checkstokloc[i].kodelokasi;
                        itemMasterStock.namalokasi = checkstokloc[i].nama;
                        itemMasterStock.stok = (int)checkstokloc[i].stok;
                        chooseitems.stocks.Add(itemMasterStock);
                    }
                }
                chooseitems.prices = new List<ItemMasterPriceListClass>();
                var pricelistlokasi = db.tblLokasis.Where(p => p.kodelokasi == kodefrom).FirstOrDefault();
                if (pricelistlokasi != null)
                {
                    var checkpriceloc = (from m in db.tblLokasiCustomerGroups.Where(p => p.kodelokasi == kodefrom)
                                         from l1 in db.tblCustomerGroups.Where(p => p.kodecustomergroup == m.kodecustomergroup)
                                         from p in db.tblDPriceLists.Where(p => p.kodepricelist ==
                                        ((l1.kodepricelist.Equals("") || l1.kodepricelist == null) ? pricelistlokasi.kodepricelist : l1.kodepricelist) &&
                                        p.kodebarang == kodebarang)
                                         group new { m, l1 } by new
                                         {
                                             l1.kodecustomergroup,
                                             l1.nama,
                                             p.hargajual,
                                             p.discjual
                                         }
                                    into g
                                         select new
                                         {
                                             g.Key.kodecustomergroup,
                                             g.Key.nama,
                                             g.Key.hargajual,
                                             g.Key.discjual
                                         }).OrderByDescending(p => p.kodecustomergroup).ToList();
                    for (int i = 0; i < checkpriceloc.Count; i++)
                    {
                        ItemMasterPriceListClass itemMasterPriceList = new ItemMasterPriceListClass();
                        itemMasterPriceList.kodecustomergroup = checkpriceloc[i].kodecustomergroup;
                        itemMasterPriceList.namacustomergroup = checkpriceloc[i].nama;
                        itemMasterPriceList.harga = (double)checkpriceloc[i].hargajual;
                        itemMasterPriceList.strharga = Convert.ToDecimal((double)checkpriceloc[i].hargajual).ToString("#,###");
                        itemMasterPriceList.disc = (double)checkpriceloc[i].discjual;
                        itemMasterPriceList.hargaNett = itemMasterPriceList.disc == 0 ? itemMasterPriceList.harga : 
                            (itemMasterPriceList.harga - (itemMasterPriceList.harga * itemMasterPriceList.disc / 100));

POSVITWeb/Views/MasterData/DetailsItemMaster.cshtml
@model POSVITWeb.Models.ItemMasterDetailsClass
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Asset/js/jquery.min.js"></script>
<script src="~/Asset/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="~/Asset/js/jquery-3.1.1.js" type="text/javascript"></script>
<script src="~/Asset/js/jquery-1-8-23-ui.min.js" type="text/javascript"></script>
<script src="~/Asset/js/bootstrap-datepicker.js" type="text/javascript"></script>
<link href="@Url.Content("~/Content/jquery-ui.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/bootstrap-datetimepicker.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Asset/css/jquery.dataTables.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/buttons.datatable.min.css")" rel="stylesheet" type="text/css" />
<script src="~/Asset/js/jquery.datatable.min.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script src="~/Asset/js/datatable.buttons.min.js"></script>
<script src="~/Asset/js/buttons.flash.min.js"></script>
<script src="~/Asset/js/buttons.html5.min.js"></script>
<script src="~/Asset/js/buttons.print.min.js"></script>
<script src="~/Asset/js/jszip.min.js"></script>
<script src="~/Asset/js/pdfmake.min.js"></script>
<script src="~/Asset/js/vfs_font.js"></script>

<script src="~/Asset/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script>
    var rowSelection;
    var rowSelection2;
    $(document).ready(function () {
        rowSelection = $('#dttest').DataTable({
            "responsive": true,
            "language": {
                "paginate": {
                    "previous": '<i class="demo-psi-arrow-left"></i>',
                    "next": '<i class="demo-psi-arrow-right"></i>'
                }
            },
            "order": [[0, "desc"]]
        });
        rowSelection2 = $('#dttest2').DataTable({
            "responsive": true,
            "language": {
                "paginate": {
                    "previous": '<i class="demo-psi-arrow-left"></i>',
                    "next": '<i class="demo-psi-arrow-right"></i>'
                }
            },
            "order": [[0, "desc"]]
        });
        $('#btncancel').click(function () {
             window.location.href = "@Url.Action("ItemMaster", "MasterData")";
        });
    })
    function onchangefile() {
        var input, file;
        if (!window.FileReader) {
            bodyAppend("p", "The file API isn't supported on this browser yet.");
            return;
        }

        input = document.getElementById('files');
        if (!input) {
            bodyAppend("p", "Um, couldn't find the fileinput element.");
        }
        else if (!input.files) {
            bodyAppend("p", "This browser doesn't seem to support the `files` property of file inputs.");
        }
        else if (!input.files[0]) {
            bodyAppend("p", "Please select a file before clicking 'Load'");
        }
        else {
            file = input.files[0];
            if (parseInt(file.size) > 1500000) {
                var reader = new FileReader();
                reader.onload = function () {
                    var data = this.result;
                    var img = new Image();
                    img.src = data;
                    img.onload = function () {
                    };
                };
                reader.readAsDataURL(file);
            }
        }
    }
</script>
<div>
    <div>
        <div id="page-content" style="font-size:14px">
            <div class="col-sm-12">
                <div class="panel panel-bordered panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Details Item Master</h3>
                    </div>
                    @using (Html.BeginForm("DetailsItemMaster", "MasterData", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
                    {
                    <div class="panel-body">
                        <div class="form-group" hidden>
                            <label class="col-sm-3 control-label" for="demo-hor-inputemail">Item Code</label>
                            <div class="col-sm-3">
                                @Html.TextBoxFor(model => model.realkodebarang, new { @type = "text", @class = "form-control" })
                            </div>
                            <label class="col-sm-1 control-label" for="demo-hor-inputemail">Nama</label>
                            <div class="col-sm-3">
                                @Html.TextBoxFor(model => model.realnama, new { @type = "text", @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="demo-hor-inputemail">Item Code</label>
                            <div class="col-sm-3">
                                @Html.TextBoxFor(model => model.kodebarang, new { @type = "text", @class = "form-control", @id = "txtnofaktur", @onchange = "onchangedatetime1()", @required = "required", @disabled = "true" })
                            </div>
                            <label class="col-sm-1 control-label" for="demo-hor-inputemail">Barcode</label>
                            <div class="col-sm-3">
                                @Html.TextBoxFor(model => model.itemcode, new { @type = "text", @class = "form-control", @id = "txtcomment", @required = "required", @maxlength = "50", @disabled = "true" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="demo-hor-inputemail">Name</label>
                            <div class="col-sm-3">
                                @Html.TextAreaFor(model => model.nama, new { @type = "text", @class = "form-control", @id = "datepicker1", @onchange = "onchangedatetime1()", @required = "required", @disabled = "true" })
                            </div>
                            <label class="col-sm-1 control-label" for="demo-hor-inputemail">Category</label>
                            <div class="col-sm-3">
                                @Html.TextBoxFor(model => model.namakategori, new { @type = "text", @class = "form-control", @id = "datepicker1", @onchange = "onchangedatetime1()", @required = "required", @disabled = "true" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="demo-hor-inputemail">Measure</label>
                            <div class="col-sm-3">
                                @Html.TextBoxFor(model => model.satuan, new { @type = "text", @class = "form-control", @id = "txtcomment", @required = "required", @maxlength = "50", @disabled = "true" })
                            </div>
                            <label class="col-sm-1 control-label" for="demo-hor-inputemail">Supplier</label>
                            <div class="col-sm-3">
                                @Html.TextBoxFor(model => model.namavendor, new { @type = "text", @class = "form-control", @id = "txtcomment", @required = "required", @maxlength = "50", @disabled = "true" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label" for="demo-hor-inputemail" hidden>Price</label>
                            <div class="col-sm-3" hidden>
                                @Html.TextBoxFor(model => model.strharga, new { @type = "text", @class = "form-control", @id = "datepicker1", @onchange = "onchangedatetime1()", @required = "required", @disabled = "true" })
                            </div>
                            <label class="col-sm-1 control-label" for="demo-hor-inputemail" hidden>Stock</label>
                            <div class="col-sm-3" hidden>
                                @Html.TextBoxFor(model => model.stok, new { @type = "text", @class = "form-control", @id = "txtcomment", @required = "required", @maxlength = "50", @disabled = "true" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <label class="col-sm-3 control-label" for="demo-hor-inputemail">Image</label>
                                <div class="col-sm-3">
                                    <img src="@Url.Action("getItemImage", "MasterData", new { kodebarang = Model.realkodebarang })" width="100px" height="100px" />
                                </div>
                                @*<label class="col-sm-1 control-label" for="demo-hor-inputemail">Image</label>
                                <div class="col-sm-3">
                                    <input type="file" id="files" name="file" onchange="onchangefile()" accept="image/*" />
                                </div>*@
                            </div>
                        </div>
                        <div class="form-group"></div>
                        <table id="dttest2" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th width="10%" style="text-align:center">Price Code</th>
                                    <th width="25%" style="text-align:center">Price Name</th>
                                    <th width="10%" style="text-align:center">Price</th>
                                    <th width="25%" style="text-align:center">Disc</th>
                                    <th width="25%" style="text-align:center">Nett Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.prices)
                                {
                                <tr>
                                    <td style="text-align:center">@item.kodecustomergroup</td>
                                    <td style="text-align:left">@item.namacustomergroup</td>
                                    <td style="text-align:right">@item.strharga</td>
                                    <td style="text-align:right">@item.disc</td>
                                    <td style="text-align:right">@item.strHargaNett</td>
                                </tr>
                                }
                            </tbody>
                        </table>
                        <div class="form-group"></div>
                        @if (Model.stocks != null)
                        {
                            <table id="dttest" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th width="10%" style="text-align:center">Location Code</th>
                                        <th width="25%" style="text-align:center">Location Name</th>
                                        <th width="10%" style="text-align:center">Stock</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.stocks)
                                    {
                                        <tr>
                                            <td style="text-align:center">@item.kodelokasi</td>
                                            <td style="text-align:left">@item.namalokasi</td>
                                            <td style="text-align:center">@item.stok</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                    </div>
                        <div class="panel-footer text-right">
                            <div class="box-inline">
                                <button type="button" id="btncancel" class="btn btn-danger" onclick="onclickcancel()"> Back</button>
                                <button type="submit" id="btnsuccess" class="btn btn-success" onclick="onclickcancel()"> Submit</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

    </div>
</div>

POSVITWeb/Views/MasterData/ItemMaster.cshtml
@model IEnumerable<POSVITWeb.Models.ItemMasterClass>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Asset/js/jquery.min.js"></script>
<script src="~/Asset/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="~/Asset/js/jquery-3.1.1.js" type="text/javascript"></script>
<script src="~/Asset/js/jquery-1-8-23-ui.min.js" type="text/javascript"></script>
<script src="~/Asset/js/bootstrap-datepicker.js" type="text/javascript"></script>
<link href="@Url.Content("~/Content/jquery-ui.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/bootstrap-datetimepicker.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Asset/css/jquery.dataTables.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/buttons.datatable.min.css")" rel="stylesheet" type="text/css" />
<script src="~/Asset/js/jquery.datatable.min.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script src="~/Asset/js/datatable.buttons.min.js"></script>
<script src="~/Asset/js/buttons.flash.min.js"></script>
<script src="~/Asset/js/buttons.html5.min.js"></script>
<script src="~/Asset/js/buttons.print.min.js"></script>
<script src="~/Asset/js/jszip.min.js"></script>
<script src="~/Asset/js/pdfmake.min.js"></script>
<script src="~/Asset/js/vfs_font.js"></script>
<script src="~/Asset/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="~/Asset/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="~/Asset/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<script>
    var rowSelection;
    $(document).ready(function () {
        
        $('#dttest tbody').on('dblclick', 'tr', function () {
            //var data = rowSelection.row(this).data();
            var data = rowSelection.rows('.selected').data();
            window.location.href = "@Url.Action("DetailsItemMaster","MasterData")?kodebarang=" + data[0].kodebarang;
        });
         $.getJSON("@Url.Action("getAllItem", "MasterData")", function (data) {
             
             rowSelection = $('#dttest').DataTable({
                data: data,
                columns: [
                    { "data": "kodebarang" },
                    { "data": "nama" },
                    { "data": "namakategori" },
                    { "data": "satuan" },
                    //{ "data": "strharga" },
                    { "data": "strStock" },
                    { "data": "barcode" }
                ],
                "responsive": true,
                "language": {
                    "paginate": {
                        "previous": '<i class="demo-psi-arrow-left"></i>',
                        "next": '<i class="demo-psi-arrow-right"></i>'
                    }
                },
                //"columnDefs": [
                //    { "className": "hidden", "targets": [4, 5] },
                //    { "className": "dt-right", "targets": [4, 5] },
                //    { "className": "dt-center", "targets": [0, 3, 6] },
                //    { "targets": [3, 4, 5], "searchable": false }
                //],
                //"order": [[0, "asc"]]
             });
             $('#dttest').on('click', 'tr', function () {
                 if ($(this).hasClass('selected')) {
                     //$(this).removeClass('selected');
                     //var data = rowSelection.rows('.selected').data();
                    
                 }
                 else {
                     rowSelection.$('tr.selected').removeClass('selected');
                     $(this).addClass('selected');
                 }
             });
        });
    })
</script>
<div>
    <div>
        <div id="page-content" style="font-size:14px">
            <div class="col-sm-12">
                <div class="panel panel-bordered panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Item Master Data</h3>
                    </div>
                    @if (ViewBag.Message != null)
                    {
                        <div class="mar-ver pad-btm">
                            <h3 class="h4 mar-no">@ViewBag.Message</h3>
                        </div>
                    }
                    <div class="panel-body">
                        <div class="form-group"></div>
                        <table id="dttest" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th width="10%" style="text-align:center">Code</th>
                                    <th width="25%" style="text-align:center">Name</th>
                                    <th width="10%" style="text-align:center">Category</th>
                                    <th width="5%" style="text-align:center">UoM</th>
                                    @*<th width="10%" style="text-align:center">Price</th>*@
                                    <th width="5%" style="text-align:center">Stock</th>
                                    <th width="10%" style="text-align:center">Barcode</th>
                                </tr>
                            </thead>
                            <tbody>
                                @*@foreach (var item in Model)
                                    {
                                    <tr>
                                        <td style="text-align:center">@item.kodebarang</td>
                                        <td>@item.nama</td>
                                        <td>@item.namakategori</td>
                                        <td style="text-align:center">@item.satuan</td>
                                        <td style="text-align:right">@item.strharga</td>
                                        <td style="text-align:center">@item.stok</td>
                                        <td style="text-align:center">
                                            <a class="btn btn-xs btn-primary add-tooltip" data-toggle="tooltip" href="~/MasterData/DetailsItemMaster?kodebarang=@item.kodebarang" data-original-title="Item" data-container="body"><i class="fa fa-edit"></i></a>
                                        </td>
                                    </tr>
                                    }*@
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>